apiVersion: v1
kind: Service
metadata:
  name: influxdb-debug
  annotations:
    metallb.universe.tf/allow-shared-ip: one
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
  type: LoadBalancer
