apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 0.2Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: influxa
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 0.2Gi
  hostPath:
    path: /data/pv0002/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  storageClassName: influxb
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 0.1Gi
  hostPath:
    path: /data/pv0003/
