apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: PMA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: PMA_DB_PASSWORD
            - name: WP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: WP_DB_PASSWORD
            - name: TG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: TG_DB_PASSWORD
            - name: ROOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: ROOT_DB_PASSWORD
            - name: PMA_DB_USER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: PMA_DB_USER
            - name: WP_DB_USER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: WP_DB_USER
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
