---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
        - name: pma
          image: pma-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: https
            - containerPort: 9090
              name: monitoring
          env:
            - name: PMA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: PMA_DB_PASSWORD
            - name: PMA_DB_USER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: PMA_DB_USER
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: mysql_server
            - name: IP_PMA
              value: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: one
spec:
  selector:
    app: pma
  ports:
    - name: https
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pma-monitoring
spec:
  selector:
    app: pma
  ports:
    - name: monitoring
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
