---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
              name: https
          env:
            - name: WP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: WP_DB_PASSWORD
            - name: WP_DB_USER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: WP_DB_USER
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: mysql_server
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: one
spec:
  selector:
    app: wordpress
  ports:
    - name: https
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-monitoring
spec:
  selector:
    app: wordpress
  ports:
    - name: monitoring
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
