apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf-image
          imagePullPolicy: Never
          env:
            - name: TG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                        name: password-secret
                        key: TG_DB_PASSWORD
            - name: mysql_server
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: mysql_server
            - name: INF_SERVER
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: influxdb_server
            - name: INF_DB_ORG
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: INF_DB_ORG
            - name: INF_DB_BASE
              valueFrom:
                configMapKeyRef:
                        name: config-all
                        key: INF_DB_BASE
            - name: INF_TOKEN
              value: INF_TOKEN_VALUE
